// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZ6eIgOeWaZoJer_OoxvquBYeG8ujAGs',
    appId: '1:869358000910:web:1f651aa56456ee857d155f',
    messagingSenderId: '869358000910',
    projectId: 'sustainability-app-b7733',
    authDomain: 'sustainability-app-b7733.firebaseapp.com',
    storageBucket: 'sustainability-app-b7733.firebasestorage.app',
    measurementId: 'G-G5ESV8HTHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgOA2LIYt1InxSGs7xhHeHulcMfnwddew',
    appId: '1:869358000910:android:e2a4a91fdc2959867d155f',
    messagingSenderId: '869358000910',
    projectId: 'sustainability-app-b7733',
    storageBucket: 'sustainability-app-b7733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdflxCU5fjRgMGvvvfQdvYPhhyaGkp6uA',
    appId: '1:869358000910:ios:32b18646963cde157d155f',
    messagingSenderId: '869358000910',
    projectId: 'sustainability-app-b7733',
    storageBucket: 'sustainability-app-b7733.firebasestorage.app',
    iosBundleId: 'com.vanagreen.app',
  );
}
